fos_oauth_server:
  db_driver: orm
  client_class: Cybalex\OauthServer\Entity\ORM\Client
  access_token_class: Cybalex\OauthServer\Entity\ORM\AccessToken
  refresh_token_class: Cybalex\OauthServer\Entity\ORM\RefreshToken
  auth_code_class: Cybalex\OauthServer\Entity\ORM\AuthCode
  service:
    user_provider: Cybalex\OauthServer\Services\ORM\UserProvider
    options:
      supported_scopes: '%env(resolve:OAUTH_SERVER_SCOPES)%'
      access_token_lifetime: '%env(resolve:OAUTH_TOKEN_LIFETIME)%'
      token_type: '%env(resolve:OAUTH_TOKEN_TYPE)%'
