security:
    encoders:
        App\Entity\User:
            algorithm:            bcrypt
            cost:                 13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_user_provider:
            id: App\Services\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

        oauth_token:
            pattern:    '^/oauth/v2/token'
            security:   false